### 머신러닝 실습
#### iris 데이터셋을 활용한 분류 모델 구축
1. 데이터셋 불러와 특징과 타겟변수 분리 (종복변수[정답]와 독립변수[입력값])
2. 데이터를 학습용과 테스트용으로 나눈다.
3. RandomForsetClassifier로 모델 학습(여기서 모델은 내가 정한다.)
- 모델에 대한 알고리즘을 지원하는 API가 있다.

4. 테스트 데이터에 대한 예측 후 정확도 평가

In [1]:
# 필요한 라이브러리 임포트
# 사이키런이 제공하는 데이터 로드
from sklearn.datasets import load_iris

# 훈련 데이터와 테스트 데이터 분리
from sklearn.model_selection import train_test_split

# 아이리스는 꽃을 분류 문제 -> RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

# 실제 정답과 모델이 예측한 결과를 비교하여 올바르게 예측한 샘플 비율을 계산해 준다.
from sklearn.metrics import accuracy_score

1. 데이터를 로드 한다.

In [2]:
iris = load_iris()

# 꽃에 대한 여러 측정값을 담은 2차 배열(행, 열{4가지})
# 꽃받침너비, 꽃받침길이, 꽃잎너비, 꽃잎길이
X = iris.data # 4가지의 특성

# 4가지의 특성을 활용하여 종속변수를 맞춰본다.- 정확도  1에 가까울 수록 높음 
y = iris.target # 정답 - 무슨꽃인지 setosa(0), versicolor(1), virginica(2)

In [3]:
type(X)

numpy.ndarray

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
type(y)

numpy.ndarray

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

2. 데이터 분할(학습용과 테스트용)

In [7]:
# 파라미터는 4가지
# 첫번째 파라미터는 특성 4가지를 가진 2차배열
# 두번째 파라미터는 종속변수 하나를 가진 1차 배열
# 세번째 파라미터는 테스트용 비율
# 네번째 파라미터는 실행시 동일한 결과를 얻기 위한 값
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
# 훈련데이터, 입력값이 4가지 종류, 4가지 특성을 파악하여 꽃을 분류
# 입력값은 보통 x축이다.
# 출력값은 보통 y축이다.
# 입력값에 따라서 출력값이 달라진다.(0, 1, 2)
X_train

array([[4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 3.2, 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 3.1, 5.5, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2

In [9]:
X_test

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2]])

In [10]:
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [11]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

3. 모델 학습(RandeomForestClassifier)

In [12]:
# 랜덤 포레스트는 여러 개의 결정  트리를 조합하여 예측하는 앙상블 기법이다.
# 100개의 결정 트리 생성하여, 각 트리의 예측 결과를  종합해 최종 예측을 수행한다.
# random_state는 모델이 데이터를 무작위로 선택하거나 분할 할 때 발생할 수 있는
# 불확실성을 동일한 방식으로 재현할 수 있게 해줌. - 여러 번 실행해도 같은 결과를 보고 싶다.
model = RandomForestClassifier(n_estimators=100, random_state=42)

# 랜덤 포레스트 모델에 학습 데이터(X_train)와 정답(y_train)을 전달하여 모델을 학습 시킨다.
# 학습 과정에서 모델은 입력데이터의 특징과 정답 간의 관계를 파악하게 되며 이를 바탕으로 새로운 데이터 예측할 수  있다.
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

4. 모델 평가

In [13]:
# 테스트 데이터에 대한 예측 및 정확도 평가
# predict 테스트 데이터 X_test를 입력받아서 학습된 모델이 각 데이터 샘플에
# 대해 예측한 결과를 반환합니다.   예측한 결과는 y_pred저장됨된다.
y_pred = model.predict(X_test)

# 실제 정답인 y_test와 랜덤 포레스트 모델이 예측한 결과인 y_pred를 비교하여
# 올바르게 예측한 샘플의 비율을 계산한다
# 이값의 결과는 0부터 1구간으로 1에 가까울 수록 모델의 예측이 정확함을 의미한다.
accuracy = accuracy_score(y_test, y_pred)
print(f"테스트 데이터 정확도 :  {accuracy: .4f}")

테스트 데이터 정확도 :   1.0000


5. 학습한 모델이나 결과를 model.pkl 파일로 저장하기

In [14]:
import pickle
with open('model.pkl', 'wb') as f:
    #pickle.dump(model, f)
    # 우리는 출력 결과를 스프링으로 내보낼 계획이니까 json으로 저장하기
    pickle.dump({'accuracy': f"{accuracy:.4f}"}, f)

5-1. model.pkl 파일 읽기

In [15]:
import pickle
with open('model.pkl', 'rb') as file:
    model = pickle.load(file)

# 모델 객체 출력(모델의 구조나 파라미터 확인 가능)
print(model)

{'accuracy': '1.0000'}


6. flask를 활용하여 5000번 포트를 열기

7. Spring 프로젝트와 연계하기