### 원 핫 인코딩     
France - (1,0) (0,0) (0,0)     
Spain - (0,0) (1,0) (0,0)    
Germany - (0,0) (0,0) (1, 0)    

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data0225/Data0227.csv")
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No'
 'Yes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


- fit() : 데이터를 이용해서 내부 파라미터를 학습할 때 사용한다.
- transform() : 이미 fit()이나 fit_transform()통해서 학습한 파라미터를 사용하여 데이터를 변환한다.
예) 학습한 평균값으로 결측치를 채우거나  학습한 표준편차로 데이터를 스케일링
- fit_transform() : fit + transform
fit(), transform()을 한 번에 실행하는 메소드 이다.
데이터를 먼저 학습을 한 후에 즉시 변환한다.

- 정리
: 처음 데이터를 학습하여 내부 파라미터를 계산하고 이를 적용하려면 fit_transform을 사용하고
이미 학습된 파라미터를 사용해 새로운 데이터나 추가 데이터에 변환만 적용하려면  transform을 사용한다.

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(X[:,1:3])

# 결측치를 평균값으로 대체하려면 transform메소드를 사용한다.
X[:,1:3] = imputer.transform(X[:,1:3])

# X데이터셋의 1번과 2번 열에서 결측치를 해당 열의 평균값으로 대체하게 된다.
# X의 대괄호 안에  , 를 기준으로 행, 열 이다.
print(X[:,1:3])

[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 63777.77777777778]
 [35.0 58000.0]
 [38.77777777777778 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]


- 첫번 째열은 원-핫 인코딩된 결과로 출력. 나머지 열은 기존 데이터 그대로 출력된다.
- 범주형 데이터를 모델 학습 전에 수치형 데이터로 쉽게 변환할 수 있다.    
- 사용 목적은 국가 정보가 문자열로 되어 있어 서로 영향이 전혀 없어야 하는 컬럼임에도
학습 과정에서 의도하지 않은 영향을 줄 수도 있으므로 보통 수치형으로 변환을 한다.
- 의도하지 않은 의미가 부여되기를 원치 않아서..... 그래서 굳이 한다.

In [ ]:
# OneHotEncoder는 범주형 데이터를 0과 1로 이루어진 이진 형태로 변환
from sklearn.preprocessing import  OneHotEncoder

# ColumnTransformer는 데이터셋의 특정 열에만 선택적으로 변환기를 적용할 수 있도록 해준다.
from sklearn.compose import ColumnTransformer

# [0]는 이름 encoder로 OneHotEncoder를 정의하고 X의 인덱스 0에 해당하는 열에만 적용해줘.
# passthrough는 지정되지 않은 다른  열들은 그대로 유지하여 변하지 않도록 한다.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder="passthrough")

# X의 0번째 열에서 학습한 후 해당 열을 원-핫 인코딩으로 변환한다
# 변환 결과는 NumPy배열로 형변환이 되어 X 에 다시 할당이 된다.
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
